### ISSUE TITLE
Page does not update stats since almost a year ago

### ISSUE THREAD

**Issue by RogueViolation** [Joopjr/Runelogger#7]
Is this plugin obsolete and should be uninstalled or is this just a bug?

**Comment by Joopjr** [comment]
Thanks for your issue!

I've not played OSRS myself for ages. The website and plugin were just online without any maintenance or care taking. You're the first person to mention that the plugin doesn't update the website.

I've looked into it straight away and found the issue. It should now have be fixed and updating again.

**Comment by RogueViolation** [comment]
Can confirm it works now. Thank you very much!
